export const ROUTES = {
  home: "/",
  aboutUs: "/about-us",
  services: "/services",
  supports: "/supports",
  ourTeam: "/our-team",
  privacyPolicy: "/privacy-policy",
  termsAndPolicy: "/terms-and-policy",
  refundPolicy: "/refund-policy",
  signUp: "/sign-up",
  signIn: "/sign-in",
  emailSent: "/email-sent",
  forgetPassword: "/forget-password",
  pricing: "/pricing",
  paymentSuccess: "/payment-success",
  player: "/player/$docId",
  resetPassword: "/reset-password/$uid/$token",
} as const;
